AZURE_OPENAI_ENDPOINT = "https://ruthv-mk14bf4j-eastus2.openai.azure.com/"
AZURE_OPENAI_KEY = "BRA3rX5nbGY7efKb6pZ7kVu3JT3LEDoguAvnveQdoGEWR1aQF226JQQJ99CAACHYHv6XJ3w3AAAAACOG29tt"
AZURE_OPENAI_DEPLOYMENT = "gpt-4.1"
AZURE_OPENAI_API_VERSION = "2024-12-01-preview"
